### PR TITLE
Use Auth Provider of Passport client.

### PR DESCRIPTION
**Pull request by merbhushan**
In existing code, we can't use any other provider apart from users but laravel passport allow us to use different provider. I modified a logic to give support of laravel passport provider and we can also configure a default provider inside configuration file.

### CODE REVIEW

**Comment by joselfonseca** [comment]
Thanks for the PR. Looks like the CI is failing and also the code style 
https://github.styleci.io/analyses/PGmMEL?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

If you can fix that I can review again and merge.

**Comment by merbhushan** [comment]
Hello @joselfonseca 

I noticed inside lighthouse php package(nuwave/lighthouse), they moved AuthDirective to separate folder but it's namespace is not being registered and because of that it started giving auth directive not found error. It's moved in 5.70 version. Can you please run a workflow for existing master branch, I think it should give a same errors?

**Comment by merbhushan** [comment]
@joselfonseca I added a fix for failing test cases. Can you please review it and merge it.

**Comment by joselfonseca** [comment]
@merbhushan looks like the test are good now, you only need to fix the style ci error and we can merge and release.

**Comment by merbhushan** [comment]
@joselfonseca Please check now.

**Pull request merged**
