### PR TITLE
Add Laravel 8 support

### PR DESCRIPTION
**Pull request by daniel-de-wit**

### CODE REVIEW

**Comment by joselfonseca** [comment]
Thanks for the PR. Unfortunately travis is failing

https://travis-ci.org/github/joselfonseca/lighthouse-graphql-passport-auth/builds/734269550

I've tried this before but there is a lot to fix when using the version 5 of lighthouse so that is why I haven't completed it.

 https://github.com/joselfonseca/lighthouse-graphql-passport-auth/issues/108

**Comment by joselfonseca** [comment]
I think you could do this.

```json
"require": {
        "php": ">=7.2.0",
        "nuwave/lighthouse": "^4.0",
        "laravel/passport": "^10.0",
        "laravel/socialite": "^5.0",
        "laravel/ui": "^3.0",
        "laravel/legacy-factories": "^1.0"
    },
    "require-dev": {
        "phpunit/phpunit" : "^9.0",
        "orchestra/testbench": "^6.0"
    },
```
That way is not failing for me. Let me know if you want to update the PR so your contribution gets merged.

**Comment by joselfonseca** [comment]
Fix #108

**Comment by daniel-de-wit** [comment]
> Thanks for the PR. Unfortunately travis is failing
> 
> https://travis-ci.org/github/joselfonseca/lighthouse-graphql-passport-auth/builds/734269550
> 
> I've tried this before but there is a lot to fix when using the version 5 of lighthouse so that is why I haven't completed it.
> 
> #108

Yeah, I saw your work before :)

Lucky for us lighthouse released 4.17 so that was my reason for sending this merge request.
Thanks for fixing it with laravel/legacy-factories 👍

**Comment by joselfonseca** [comment]
yeah, Thank you for the PR!. Version 5.1 should work on Laravel 8 now.

**Pull request merged**
