### PR TITLE
Feature/laravel-11

### PR DESCRIPTION
**Pull request by surajj2024**
upgrad the passport version and jwt version

### CODE REVIEW

**Review by surajj2024 — COMMENTED** [review]
It just basicall added the new feature when we are using laravel 11 version

**Comment by SlyDave** [comment]
This doesn't work, you can't use jwt 5.0 with this package atm, larger changes are needed as password grants have been disabled by default and the refreshToken method has been removed.

**Comment by surajj2024** [comment]
> This doesn't work, you can't use jwt 5.0 with this package atm, larger changes are needed as password grants have been disabled by default and the refreshToken method has been removed.

Thanks for your response,
Please suggest to me how can I upgrade my current project to Laravel 11.

**Comment by SlyDave** [comment]
>Thanks for your response,
Please suggest to me how can I upgrade my current project to Laravel 11.

I've had to fork the project and set `"lcobucci/jwt": "^4.0"` in `composer.json` Laravel 11 supports jwt 4.0 for now, so this does work, but in future this package is going to need to upgrade to jwt 5.0 which is a bit more involved

**Comment by joselfonseca** [comment]
Done in this PR https://github.com/joselfonseca/lighthouse-graphql-passport-auth/pull/179

**Pull request closed without merging**
